# Numpy
> Numpy is a low level library written in C (and fortan) for high level mathematical functions. NumPy cleverly overcomes the problem of running slower algorithms on Python by using multidimensional arrays and functions that operate on arrays. Any algorithm can then be expressed as a function on arrays, allowing the algorithms to be run quicky.

### Applications of Numpy

1. A powerful N-dimensional array object.
2. Sophisticated (broadcasting) functions.
3. Tools for integrating C/C++ and fortan code.
4. Useful linear algebra, Fourier transform and random number capabilities.

### Properties of ND Array
1. Homogenous - Only one datatype can be stored.
2. Only be Numbers (Numbers, Float, Complex)
3. Fixed Item Size.


## Creating Numpy Arrays
There were six methods by which we can create numpy arrays-
1. np.array() - 1D and 2D
2. np.zeros/ones/empty/random
3. np.arange()
4. np.linspace()
5. Copy()
6. Identity()

In [4]:
# Creating numpy/nd array
# Firstly we need to import the numpy library to our code.
import numpy as np # np is an alias

In [5]:
# Firsty way for creating the array in numpy is the np.array() method.
arr1 = np.array([1,2,3,4,5])
print(arr1) # Printing the array.

[1 2 3 4 5]


In [6]:
# Printing the type of the array.
type(arr1)

numpy.ndarray

In [7]:
# Creating a 2-dimensional array.
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Creating the array via the other functions.
# np.zeros(tuple(row, columns))

arr3 = np.zeros((2,3)) # Kinda similar to initializing.
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4 = np.ones((3,3))
arr4

# NOTE: The by default the datatype created by the ones and zeros method is float.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr6 = np.arange(10) # Range generates a list in a given range and arange generates an array in a given range.
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
 # Similar to the range function.
 # np.arange(from, to, step_count)
 arr7 = np.arange(5,20, 2)
 arr7

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [13]:
# If we want the lineary spaced numbers then we can use the np.linspace() method.
# np.linspace(lower_bound, upper_bound, numbers_we_want)

arr8 = np.linspace(2,10, 5)
arr8

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
# copy() function for copying a numpy array.
arr9 = arr8.copy()
arr9

array([ 2.,  4.,  6.,  8., 10.])

## Numpy Array Properties and Attributes 
> Numpy is a class so it has properties and attributes.

1. Shape
2. nDim
3. Size
4. Itemsize
5. Dtype
6. astype()

In [16]:
arr1

array([1, 2, 3, 4, 5])

In [17]:
# Shape property.
arr1.shape

(5,)

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr2.shape

(2, 3)

In [22]:
# Creating a three dimensional array.
arr_3d = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
arr_3d.shape # So it has 2 rows and 2 columns and how many arrays are there 2. So shape would be
# (2,2,2)

(2, 2, 2)

In [29]:
# If we have to check how many dimension matrix it is so we can use the ndim attribute for that.
print(arr_3d.ndim) # 3 dimension
print(arr9.ndim) # 1 dimension

3
1


In [31]:
# How to access the size of the array by size attribute.
arr1.size

5

In [32]:
 # Itemsize - Per item size.
 arr1

array([1, 2, 3, 4, 5])

In [34]:
arr1.itemsize # Here integer
# Integer 64 bit size.

8

In [35]:
arr8

array([ 2.,  4.,  6.,  8., 10.])

In [36]:
arr8.itemsize

8

In [37]:
# Dtype - datatype.
arr8.dtype

dtype('float64')

In [38]:
arr9

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
arr9.dtype

dtype('float64')

In [40]:
arr1

array([1, 2, 3, 4, 5])

In [41]:
arr1.dtype

dtype('int64')

In [42]:
# astype function which takes the datatype as parameter so they gets converted to that.
# arr1 has the int64 datatype I want to convert them to float.
arr1.astype("float") # This method is kinda useful in data cleaning and all.

array([1., 2., 3., 4., 5.])

## Numpy Array VS Python Lists
Numpy arrays has several advantages over normal lists.
1. Faster
2. Convenient
3. Less Memory

#### Numpy arrays takes less memory than traditional lists.

In [44]:
# Creating a list and creating a numpy array and checking how much memory they are taking.

lista = range(100)
nparr = np.arange(100)

In [45]:
# For getting the size we have the getsizeof function inside the sys module.
import sys

In [46]:
print(sys.getsizeof(87)*len(lista))

2800


In [47]:
print(nparr.itemsize*nparr.size)

800


### Faster execution and conviency
Performing addition of two entities list and arrays and figuring out how fast execution is done in numpy.

In [49]:
import time

In [53]:
x = range(10000000)
y = range(10000000, 20000000)

start_time = time.time()
z = [x+y for x,y in zip(x,y)]

print(f"Time taken by lists: {time.time() - start_time}")

Time taken by lists: 2.8104937076568604


In [54]:
a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start_time = time.time()
c = a+b # If you have to add two arrays simply do this.and
print(f"Time taken by numpy arrays: {time.time()-start_time}")

Time taken by numpy arrays: 0.08272600173950195
